[functions]
  directory = "src/functions"
  node_bundler = "esbuild"

[build]
  command = "npm run prod"
  publish = "dist"
[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "./dist/img/cache",
    ".cache"
  ]

[[plugins]]
package = "netlify-plugin-debug-cache"

[dev]
  autoLaunch = false
